MODEL:
  VID:
    RPN:
      # 300 rois for selsa
      REF_POST_NMS_TOP_N: 75
    METHOD: "mamba"
    MAMBA:
      REF_NUM: 4
      SHUFFLE_TEST: True
      PIX_MEM:
        ENABLE: True
        GEO:
          OUTPUT_TYPE: "alignment"
          USE_EYE_INIT: True
      INS_MEM:
        ENABLE: True
  META_ARCHITECTURE: "GeneralizedRCNNMAMBA"
  WEIGHT: "training_dir/MAMBA/vid_X_101_C4_INS_stride_false_1x/model_last_pure.pth"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "MAMBAFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
OUTPUT_DIR: "training_dir/MAMBA/vid_X_101_C4_PIX_alignment_eye_1x_INS_stride_false_ref4_1x"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, )
  MAX_ITER: 120000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 40000
