MODEL:
  VID:
    RPN:
      # 300 rois for selsa
      REF_POST_NMS_TOP_N: 75
    METHOD: "mamba"
    MAMBA:
      REF_NUM: 0
      SHUFFLE_TEST: False
      PIX_MEM:
        ENABLE: False
      INS_MEM:
        ENABLE: False
  META_ARCHITECTURE: "GeneralizedRCNNMAMBA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNetConv52MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
OUTPUT_DIR: "training_dir/MAMBA/vid_R_101_C4_1x"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, )
  MAX_ITER: 120000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 40000
