MODEL:
  VID:
    RPN:
      # 300 rois for selsa
      REF_POST_NMS_TOP_N: 75
    METHOD: "mamba"
    MAMBA:
      SHUFFLE_TEST: True
      PIX_MEM:
        ENABLE: True
        USE_RELU: True
        GEO:
          OUTPUT_TYPE: "alignment"
          USE_EYE_INIT: True
      INS_MEM:
        ENABLE: False
  META_ARCHITECTURE: "GeneralizedRCNNMAMBA"
  WEIGHT: "training_dir/MAMBA/vid_R_101_C4_0x/model_last_pure.pth"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "ResNetConv52MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
OUTPUT_DIR: "training_dir/MAMBA/vid_R_101_C4_PIX_alignment_eye_relu_0x"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, )
  MAX_ITER: 60000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 20000
